---
- name: Install requirements
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - glibc-locale-source
    - glibc-langpack-en

- name: Check the current locale
  ansible.builtin.command: localectl
  changed_when: false
  register: current_locale

- name: Create locale ja_JP.UTF-8
  ansible.builtin.command:
    localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
  register: locale_created
  changed_when: locale_created.rc == 0
  when:
    - '"ja_JP.UTF-8" not in current_locale.stdout'

- name: Set locale to ja_JP.UTF-8
  ansible.builtin.command:
    localectl set-locale LANG=ja_JP.UTF-8
  register: locale_set
  changed_when: locale_set.rc == 0
  when:
    - '"ja_JP.UTF-8" not in current_locale.stdout'
